//
// Created by Luecx on 04.06.2021.
//

#ifndef ENGINE3D_SRC_ENTITIES_COMPONENTS_COMPONENT_H_
#define ENGINE3D_SRC_ENTITIES_COMPONENTS_COMPONENT_H_

namespace ecs{

struct Component{};

}

#endif    // ENGINE3D_SRC_ENTITIES_COMPONENTS_COMPONENT_H_
